smart  commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,39 @@
 name: Build and Deploy
 
 on:
-    push:
-        branches:
-            - master
+  push:
+    branches:
+      - master
 
 jobs:
-    deploy: 
-        runs-on: ubuntu-latest
+  deploy:
+    runs-on: ubuntu-latest
 
-        steps:
-            - name: Checkout Code
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-            - name: set up Terraform
-              uses: hashicorp/setup-terraform@v1
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v1
 
-            - name: Terraform Initialize
-              run: | 
-                cd aws_infra
-                terraform init
+      - name: Terraform Plan with AWS Credentials
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        run: echo "AWS credentials are set"
 
-            - name: Terraform Plan
-              run: |
-                    cd aws_infra
-                    terraform plan
-                    if [ $? -eq 0 ]; then  
-                        echo "Step two successful: Terraform plan succeeded"
-                    else
-                        echo "Terraform plan failed" >&2
-                        exit 1  # Fail the step if plan fails
-                    fi
-                    else
-                        echo "No Terraform configuration files found in aws_infra directory" >&2
-                        exit 1
-                    fi
+      - name: Terraform Initialize
+        run: |
+          cd aws_infra
+          terraform init
+
+      - name: Terraform Plan
+        run: |
+          cd aws_infra
+          terraform plan
+          if [ $? -eq 0 ]; then  
+              echo "Step two successful: Terraform plan succeeded"
+          else
+              echo "Terraform plan failed" >&2
+              exit 1  # Fail the step if plan fails
+          fi
