smart  commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,30 +10,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Checkout the repository
       - name: Checkout Code
         uses: actions/checkout@v2
 
+      # Set up Terraform CLI
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v1
 
-      - name: Terraform Initialize
+      # Initialize and Plan Terraform with Secrets
+      - name: Terraform Init and Plan
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          # Load variables from GitHub Secrets
+          TF_VAR_name: ${{ secrets.TF_VAR_name }}
+          TF_VAR_vpc_cidr_block: ${{ secrets.TF_VAR_vpc_cidr_block }}
+          TF_VAR_azs: ${{ secrets.TF_VAR_azs }}
+          TF_VAR_node_group_1_instance_type: ${{ secrets.TF_VAR_node_group_1_instance_type }}
+          TF_VAR_rds_instance1_password: ${{ secrets.TF_VAR_rds_instance1_password }}
+
         run: |
           cd aws_infra
           terraform init
-
-      - name: Terraform Plan
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        run: |
-          cd aws_infra
           terraform plan
-          if [ $? -eq 0 ]; then  
-              echo "Step two successful: Terraform plan succeeded"
+          if [ $? -eq 0 ]; then
+              echo "Terraform plan succeeded."
           else
-              echo "Terraform plan failed" >&2
+              echo "Terraform plan failed." >&2
               exit 1  # Fail the step if plan fails
           fi
